[project]
name = "r-RcppDPR"
channels = ["dnachun", "conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[system-requirements]
libc = { family="glibc", version="2.17" }

[tasks]
devtools_document = "R -e 'devtools::document()'"
devtools_test = "R -e 'devtools::test()'"
codecov = "R -e 'covr::codecov(quiet = FALSE)'"
rcmdcheck = "R -e 'rcmdcheck::rcmdcheck()'"

[feature.r43]
dependencies = {"r-base" = "4.3.*"}

[feature.r44]
dependencies = {"r-base" = "4.4.*"}

[environments]
r43 = {features = ["r43"]}
r44 = {features = ["r44"]}

[target.linux-64.dependencies]

[target.linux-64.dependencies]
"gcc" = "*"

[dependencies]
"bioconductor-snpstats" = "*"
"gsl" = "*"
"r-devtools" = "*"
"r-rcmdcheck" = "*"
"r-covr" = "*"
"r-rcpp" = "*"
"r-rcpparmadillo" = "*"
"r-rcppgsl" = "*"
