# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run <- function(y, W, G, UtX, ni_test, n_cvt, ns_test, l_min, l_max, n_region, l_remle_null, logl_remle_H0, pve_null, pve_se_null, vg_remle_null, ve_remle_null, n_k, w_step, s_step) {
    invisible(.Call(`_DPR_run`, y, W, G, UtX, ni_test, n_cvt, ns_test, l_min, l_max, n_region, l_remle_null, logl_remle_H0, pve_null, pve_se_null, vg_remle_null, ve_remle_null, n_k, w_step, s_step))
}

test_run <- function(y) {
    invisible(.Call(`_DPR_test_run`, y))
}

rcpp_hello <- function() {
    .Call(`_DPR_rcpp_hello`)
}

