# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_gibbs_without_u_screen <- function(y, W, UtX, n_k = 4L, w_step = 1000L, s_step = 1000L, l_min = 1e-7, l_max = 1e5, n_region = 10L) {
    .Call(`_RcppDPR_run_gibbs_without_u_screen`, y, W, UtX, n_k, w_step, s_step, l_min, l_max, n_region)
}

run_VB <- function(y, W, X, n_k = 4L, l_min = 1e-7, l_max = 1e5, n_region = 10L) {
    .Call(`_RcppDPR_run_VB`, y, W, X, n_k, l_min, l_max, n_region)
}

rcpp_hello <- function() {
    .Call(`_RcppDPR_rcpp_hello`)
}

