# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_VB <- function(y, W, X, n_k = 4L, l_min = 1e-7, l_max = 1e5, n_region = 10L, show_progress = TRUE) {
    .Call(`_RcppDPR_run_VB`, y, W, X, n_k, l_min, l_max, n_region, show_progress)
}

run_VB_custom_kinship <- function(y, W, X, G, n_k = 4L, l_min = 1e-7, l_max = 1e5, n_region = 10L, show_progress = TRUE) {
    .Call(`_RcppDPR_run_VB_custom_kinship`, y, W, X, G, n_k, l_min, l_max, n_region, show_progress)
}

run_VB_no_kinship <- function(y, W, X, n_k = 4L, l_min = 1e-7, l_max = 1e5, n_region = 10L, show_progress = TRUE) {
    .Call(`_RcppDPR_run_VB_no_kinship`, y, W, X, n_k, l_min, l_max, n_region, show_progress)
}

run_gibbs_without_u_screen <- function(y, W, X, n_k = 4L, w_step = 1000L, s_step = 1000L, l_min = 1e-7, l_max = 1e5, n_region = 10L, show_progress = TRUE) {
    .Call(`_RcppDPR_run_gibbs_without_u_screen`, y, W, X, n_k, w_step, s_step, l_min, l_max, n_region, show_progress)
}

run_gibbs_without_u_screen_custom_kinship <- function(y, W, X, G, n_k = 4L, w_step = 1000L, s_step = 1000L, l_min = 1e-7, l_max = 1e5, n_region = 10L, show_progress = TRUE) {
    .Call(`_RcppDPR_run_gibbs_without_u_screen_custom_kinship`, y, W, X, G, n_k, w_step, s_step, l_min, l_max, n_region, show_progress)
}

run_gibbs_without_u_screen_no_kinship <- function(y, W, X, n_k = 4L, w_step = 1000L, s_step = 1000L, l_min = 1e-7, l_max = 1e5, n_region = 10L, show_progress = TRUE) {
    .Call(`_RcppDPR_run_gibbs_without_u_screen_no_kinship`, y, W, X, n_k, w_step, s_step, l_min, l_max, n_region, show_progress)
}

run_gibbs_without_u_screen_adaptive <- function(y, W, X, m_n_k = 6L, w_step = 1000L, s_step = 1000L, l_min = 1e-7, l_max = 1e5, n_region = 10L, show_progress = TRUE) {
    .Call(`_RcppDPR_run_gibbs_without_u_screen_adaptive`, y, W, X, m_n_k, w_step, s_step, l_min, l_max, n_region, show_progress)
}

run_gibbs_without_u_screen_adaptive_custom_kinship <- function(y, W, X, G, m_n_k = 6L, w_step = 1000L, s_step = 1000L, l_min = 1e-7, l_max = 1e5, n_region = 10L, show_progress = TRUE) {
    .Call(`_RcppDPR_run_gibbs_without_u_screen_adaptive_custom_kinship`, y, W, X, G, m_n_k, w_step, s_step, l_min, l_max, n_region, show_progress)
}

run_gibbs_without_u_screen_adaptive_no_kinship <- function(y, W, X, m_n_k = 6L, w_step = 1000L, s_step = 1000L, l_min = 1e-7, l_max = 1e5, n_region = 10L, show_progress = TRUE) {
    .Call(`_RcppDPR_run_gibbs_without_u_screen_adaptive_no_kinship`, y, W, X, m_n_k, w_step, s_step, l_min, l_max, n_region, show_progress)
}

