name: Continuous Integration

on:
  pull_request:
    paths-ignore:
      - .github/*
      - .gitignore
      - README.md

jobs:
  ci_linux-64:
    name: linux-64 CI
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        environment: ["r43", "r44"]
    
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1

      # - name: Run unit tests
      #   run: pixi run --environment ${{ matrix.environment }} devtools_test

      # - name: Check unit test code coverage
      #   run: pixi run --environment ${{ matrix.environment }} codecov

      - name: Run R CMD CHECK
        run: |
          pixi install --environment ${{ matrix.environment }}
          ls -la .pixi/envs/default/lib
          ln -sf .pixi/envs/default/lib/libhwasan.so.0 .pixi/envs/default/lib/libhwasan.so
          ln -sf .pixi/envs/${{ matrix.environment }}/lib/libhwasan.so.0 .pixi/envs/${{ matrix.environment }}/lib/libhwasan.so
          pixi run --environment ${{ matrix.environment }} rcmdcheck

  ci_osx-64:
    name: osx-64 CI
    runs-on: macos-13
    env:
      MACOSX_DEPLOYMENT_TARGET: 11.0
    strategy:
      fail-fast: false
      matrix:
        environment: ["r43", "r44"]
    
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1

      - name: Disable LIBCPP_AVAILABILITY
        shell: pixi exec --spec sed  -- bash -e {0}
        run:
          sed -i 's/PKG_CXXFLAGS = /PKG_CXXFLAGS = -D_LIBCPP_DISABLE_AVAILABILITY/' src/Makevars.in

      - name: Run unit tests
        run: pixi run --environment ${{ matrix.environment }} devtools_test

      - name: Run R CMD CHECK
        run: pixi run --environment ${{ matrix.environment }} rcmdcheck
  
  ci_osx-arm64:
    name: osx-arm64 CI
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        environment: ["r43", "r44"]
    
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1

      - name: Run unit tests
        run: pixi run --environment ${{ matrix.environment }} devtools_test

      - name: Run R CMD CHECK
        run: pixi run --environment ${{ matrix.environment }} rcmdcheck
